import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import {
  Activity, AlertTriangle, CheckCircle2, CircleGauge, Cpu, HardDrive,
  LayoutDashboard, LogOut, MemoryStick, Network, RefreshCw, Search,
  Server, Settings, ShieldAlert, Terminal, Thermometer, User, FileText,
  Wrench, Menu, X, Bell, BrainCircuit
} from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import "./styles.css";

const API = import.meta.env.VITE_API_URL || "http://localhost:8000";
const demoServers = [
  {instance:"dc-prod-01:9100",hostname:"dc-prod-01",status:"UP",environment:"production",role:"application",cpu:42,memory:61,disk:68,temperature:54,health_score:94,network_rx_bps:120000000,network_tx_bps:84000000,uptime_seconds:1555200},
  {instance:"dc-prod-02:9100",hostname:"dc-prod-02",status:"UP",environment:"production",role:"application",cpu:68,memory:73,disk:76,temperature:59,health_score:82,network_rx_bps:93000000,network_tx_bps:64000000,uptime_seconds:1238400},
  {instance:"dc-db-01:9100",hostname:"dc-db-01",status:"UP",environment:"database",role:"database",cpu:34,memory:82,disk:71,temperature:57,health_score:86,network_rx_bps:44000000,network_tx_bps:39000000,uptime_seconds:1814400},
  {instance:"dc-edge-01:9100",hostname:"dc-edge-01",status:"DOWN",environment:"edge",role:"edge",cpu:0,memory:0,disk:0,temperature:null,health_score:0,network_rx_bps:0,network_tx_bps:0,uptime_seconds:0}
];
const demoAlerts=[
 {labels:{severity:"critical",alertname:"ServerDown",instance:"dc-edge-01:9100"},annotations:{description:"Server has been unreachable for more than 1 minute."},status:{state:"active"}},
 {labels:{severity:"warning",alertname:"HighMemoryUsage",instance:"dc-db-01:9100"},annotations:{description:"Memory usage is above the warning threshold."},status:{state:"active"}}
];
const demoHistory=Array.from({length:20},(_,i)=>({time:`-${20-i}m`,cpu:35+((i*11)%38),memory:56+((i*7)%30)}));

function api(path, options={}) {
  const token=localStorage.getItem("dc_token");
  return fetch(`${API}${path}`,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}}).then(async r=>{
    if(r.status===401){localStorage.removeItem("dc_token");window.dispatchEvent(new Event("logout"));throw new Error("Authentication required")}
    if(!r.ok) throw new Error((await r.json().catch(()=>({detail:r.statusText}))).detail||r.statusText);
    return r.json();
  });
}

function Login({onLogin}) {
 const [username,setUsername]=useState("admin"),[password,setPassword]=useState("admin"),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 async function submit(e){e.preventDefault();setLoading(true);setError("");try{const d=await api("/api/auth/login",{method:"POST",body:JSON.stringify({username,password})});localStorage.setItem("dc_token",d.access_token);onLogin(d)}catch(e){setError(e.message)}finally{setLoading(false)}}
 return <div className="loginShell"><div className="loginGlow"/><form className="loginCard" onSubmit={submit}><div className="brand large"><div className="brandIcon"><Server size={24}/></div><div><b>DC Monitor</b><span>Infrastructure Operations Center</span></div></div><div className="loginTitle">Secure Operations Access</div><p className="muted">Sign in to monitor servers, alerts and infrastructure health.</p>{error&&<div className="error">{error}</div>}<label>Username<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><button className="primary wide" disabled={loading}>{loading?"Authenticating…":"Sign in"} <ShieldAlert size={16}/></button><div className="loginHint">Demo credentials: admin / admin</div></form></div>
}

function App(){
 const [session,setSession]=useState(null),[page,setPage]=useState("overview"),[servers,setServers]=useState(demoServers),[alerts,setAlerts]=useState(demoAlerts),[overview,setOverview]=useState({servers_total:4,servers_up:3,servers_down:1,critical_servers:1,warning_servers:1,avg_cpu:46,avg_memory:72,avg_disk:67,network_bps:409000000,active_alerts:2,resolved_alerts:0,monitoring_uptime:"DEMO MODE"}),[demo,setDemo]=useState(true),[last,setLast]=useState(new Date()),[search,setSearch]=useState(""),[loading,setLoading]=useState(false),[mobile,setMobile]=useState(false);
 useEffect(()=>{const token=localStorage.getItem("dc_token");if(token)api("/api/auth/me").then(setSession).catch(()=>{});const logout=()=>setSession(null);window.addEventListener("logout",logout);return()=>window.removeEventListener("logout",logout)},[]);
 const refresh=async()=>{if(!session)return;setLoading(true);try{const [o,s,a]=await Promise.all([api("/api/overview"),api("/api/servers"),api("/api/alerts")]);setOverview(o);setServers(s);setAlerts(a);setDemo(false)}catch(e){setDemo(true)}finally{setLast(new Date());setLoading(false)}};
 useEffect(()=>{if(session){refresh();const id=setInterval(refresh,30000);return()=>clearInterval(id)}},[session]);
 if(!session)return <Login onLogin={setSession}/>;
 const active=alerts.filter(a=>a.status?.state==="active").length;
 const filtered=useMemo(()=>servers.filter(s=>(s.instance+" "+s.hostname+" "+s.environment+" "+s.role).toLowerCase().includes(search.toLowerCase())),[servers,search]);
 const nav=[["overview","Overview",LayoutDashboard],["servers","Servers",Server],["alerts","Alerts",ShieldAlert],["metrics","Metrics",Activity],["anomaly","Anomaly Lab",BrainCircuit],["audit","Audit & Logs",FileText],["maintenance","Maintenance",Wrench],["settings","Settings",Settings]];
 return <div className="app"><aside className={`sidebar ${mobile?"open":""}`}><div className="brand"><div className="brandIcon"><Server size={22}/></div><div><b>DC Monitor</b><span>Operations Center</span></div>{mobile&&<button className="iconBtn close" onClick={()=>setMobile(false)}><X/></button>}</div><nav>{nav.map(([id,label,Icon])=><button key={id} className={`nav ${page===id?"active":""}`} onClick={()=>{setPage(id);setMobile(false)}}><Icon size={17}/>{label}{id==="servers"&&<span>{servers.length}</span>}{id==="alerts"&&<span>{active}</span>}</button>)}</nav><div className="sideBottom"><div className="live"><i/>{demo?"Demo Mode":"Monitoring Active"}</div><small>Prometheus • Grafana • Alertmanager</small><small>Signed in as <b>{session.username}</b> · {session.role}</small></div></aside><main><header><div className="mobileMenu"><button className="iconBtn" onClick={()=>setMobile(true)}><Menu/></button></div><div><div className="eyebrow">INFRASTRUCTURE / {page.toUpperCase()}</div><h1>{nav.find(x=>x[0]===page)?.[1]||"Overview"}</h1><p>Real-time Linux infrastructure observability and alert management.</p></div><div className="headerActions">{demo&&<div className="demoBadge">DEMO MODE</div>}<button className="refresh" onClick={refresh} disabled={loading}><RefreshCw size={15} className={loading?"spin":""}/> Refresh</button><div className="avatar">{session.username.slice(0,2).toUpperCase()}</div><button className="iconBtn" title="Logout" onClick={()=>{localStorage.removeItem("dc_token");setSession(null)}}><LogOut size={16}/></button></div></header>
 {page==="overview"&&<Overview overview={overview} servers={servers} alerts={alerts} demo={demo} search={search} setSearch={setSearch} filtered={filtered} last={last} setPage={setPage}/>}
 {page==="servers"&&<Servers servers={filtered} search={search} setSearch={setSearch} onSelect={()=>setPage("metrics")}/>}
 {page==="alerts"&&<Alerts alerts={alerts} role={session.role}/>}
 {page==="metrics"&&<Metrics servers={servers}/>}
 {page==="anomaly"&&<Anomaly/>}
 {page==="audit"&&<Audit/>}
 {page==="maintenance"&&<Maintenance/>}
 {page==="settings"&&<SettingsPage/>}
 <footer><span>DC Monitor v2.0 · Enterprise-style observability demo</span><span>React • FastAPI • Prometheus • Grafana • Alertmanager • Docker</span></footer></main></div>
}

function Overview({overview,servers,alerts,demo,search,setSearch,filtered,last,setPage}){const active=alerts.filter(a=>a.status?.state==="active");return <><section className="kpis">{[
 ["Servers Online",overview.servers_up,"good",CheckCircle2],["Servers Offline",overview.servers_down,"danger",AlertTriangle],["Avg CPU",`${overview.avg_cpu}%`,"",Cpu],["Avg Memory",`${overview.avg_memory}%`,"",MemoryStick],["Avg Disk",`${overview.avg_disk}%`,"",HardDrive],["Network",formatBps(overview.network_bps),"",Network]
].map(([label,value,tone,Icon])=><Kpi key={label} icon={<Icon/>} label={label} value={value} tone={tone}/>)}</section><section className="grid2"><Card title="Resource utilization" subtitle="Prometheus time-series · demo trend when no targets are connected"><div className="chartLegend"><span>● CPU</span><span>● Memory</span></div><ResponsiveContainer width="100%" height={280}><AreaChart data={demoHistory}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="time"/><YAxis domain={[0,100]} unit="%"/><Tooltip/><Area type="monotone" dataKey="cpu" stroke="var(--cyan)" fill="var(--cyan)" fillOpacity=".08"/><Area type="monotone" dataKey="memory" stroke="var(--purple)" fill="var(--purple)" fillOpacity=".07"/></AreaChart></ResponsiveContainer></Card><Card title="Alert center" subtitle="Deterministic Prometheus rules + Alertmanager"><div className="alertList">{active.slice(0,5).map((a,i)=><AlertRow key={i} alert={a}/>)}{!active.length&&<Empty title="No active alerts" text="Your monitored infrastructure is within configured thresholds."/>}</div><div className="alertFooter"><span><span className="pulse"/>{active.length} active alerts</span><button className="linkBtn" onClick={()=>setPage("alerts")}>Open alert management →</button></div></Card></section><section className="card"><div className="cardHeader"><div><h2>Server inventory</h2><p>Health score is a transparent project-defined composite, not an industry standard.</p></div><div className="search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search host, role, environment…"/></div></div><ServerTable servers={filtered}/><div className="tableFooter">Showing {filtered.length} of {servers.length} · Last sync {last.toLocaleTimeString()}<span>{demo?"Demo data is clearly separated from live Prometheus data.":"Live Prometheus data"}</span></div></section></>}
function Servers({servers,search,setSearch,onSelect}){return <section className="card"><div className="cardHeader"><div><h2>Server inventory</h2><p>Click a host to inspect its time-series metrics.</p></div><div className="search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search…"/></div></div><ServerTable servers={servers} onSelect={onSelect}/></section>}
function ServerTable({servers,onSelect}){return <div className="tableWrap"><table><thead><tr><th>SERVER</th><th>STATUS</th><th>ENV / ROLE</th><th>CPU</th><th>MEMORY</th><th>DISK</th><th>TEMP</th><th>HEALTH</th></tr></thead><tbody>{servers.map((s,i)=><tr key={i} onClick={()=>onSelect?.(s)} className={onSelect?"clickable":""}><td><div className="serverName"><div className="serverMini"><Server size={16}/></div><div><b>{s.hostname||s.instance}</b><small>{s.instance}</small></div></div></td><td><Status status={s.status}/></td><td><span className="env">{s.environment}</span><small className="sub">{s.role}</small></td><td><Meter value={s.cpu}/></td><td><Meter value={s.memory}/></td><td><Meter value={s.disk}/></td><td>{s.temperature?`${s.temperature}°C`:"Unavailable"}</td><td><Health value={s.health_score}/></td></tr>)}</tbody></table></div>}
function Alerts({alerts,role}){const [filter,setFilter]=useState("all"),[q,setQ]=useState("");const rows=alerts.filter(a=>(filter==="all"||a.labels?.severity===filter)&&(JSON.stringify(a).toLowerCase().includes(q.toLowerCase())));return <section className="card"><div className="cardHeader"><div><h2>Alert management</h2><p>Acknowledge operational alerts; resolution remains controlled by Alertmanager.</p></div><div className="toolbar"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All severity</option><option>critical</option><option>warning</option><option>info</option><option>emergency</option></select><div className="search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search alerts…"/></div></div></div>{rows.length?<div className="alertTable">{rows.map((a,i)=><div className="alertItem" key={i}><div className={`severity ${a.labels?.severity}`}>{a.labels?.severity||"info"}</div><div><b>{a.labels?.alertname}</b><p>{a.annotations?.description}</p><small>{a.labels?.instance||"platform"} · {a.status?.state}</small></div><button className="secondary" disabled={role==="VIEWER"}>Acknowledge</button></div>)}</div>:<Empty title="No matching alerts" text="Try another severity or search term."/>}</section>}
function Metrics({servers}){const [selected,setSelected]=useState(servers[0]?.instance||"");const s=servers.find(x=>x.instance===selected)||servers[0];return <><section className="card"><div className="cardHeader"><div><h2>Server detail & time-series</h2><p>Prometheus remains the source of truth for historical metrics.</p></div><select value={selected} onChange={e=>setSelected(e.target.value)}>{servers.map(x=><option key={x.instance}>{x.instance}</option>)}</select></div>{s?<div className="detailGrid">{[["CPU",s.cpu,Cpu],["Memory",s.memory,MemoryStick],["Disk",s.disk,HardDrive],["Temperature",s.temperature??"N/A",Thermometer],["Load",s.load??"N/A",Activity],["Uptime",formatUptime(s.uptime_seconds),CheckCircle2]].map(([n,v,I])=><div className="metricTile" key={n}><I size={18}/><span>{n}</span><b>{typeof v==="number"&&n!=="Load"?`${v}%`:v}{n==="Temperature"&&typeof v==="number"?"°C":""}</b></div>)}</div>:<Empty title="No servers" text="Connect Node Exporter targets in Prometheus."/>}</section><section className="card"><h2>Operational charts</h2><p className="muted">For full historical exploration, open the provisioned Grafana dashboard at <b>http://localhost:3000</b>.</p></section></>}
function Anomaly(){const [data,setData]=useState(null);useEffect(()=>{api("/api/anomaly").then(setData).catch(()=>setData({experimental:true,findings:[]}))},[]);return <section className="card"><div className="sectionIcon"><BrainCircuit/><div><h2>Experimental anomaly detection</h2><p>Separate from deterministic Prometheus alerts. The production path can be upgraded to moving-average, z-score or Isolation Forest baselines.</p></div></div>{data?.findings?.map((x,i)=><div className="anomalyRow" key={i}><span className={x.anomaly?"dotDanger":"dotGood"}/><b>{x.instance}</b><span>{x.anomaly?"Anomaly candidate":"Normal baseline"}</span><small>{x.reasons.join(", ")||"No rule-based anomaly signals"}</small></div>)}</section>}
function Audit(){const [data,setData]=useState([]);useEffect(()=>{api("/api/audit").then(setData).catch(()=>{})},[]);return <section className="card"><h2>Audit & security activity</h2><p>Administrative actions are recorded for the current API process.</p><div className="auditList">{data.length?data.map((x,i)=><div key={i}><time>{new Date(x.timestamp).toLocaleString()}</time><b>{x.action}</b><span>{x.user} · {x.role}</span><small>{x.details}</small></div>):<Empty title="No audit events yet" text="Login, alert and maintenance actions will appear here."/>}</div></section>}
function Maintenance(){const [items,setItems]=useState([]);useEffect(()=>{api("/api/maintenance").then(setItems).catch(()=>{})},[]);return <section className="card"><div className="sectionIcon"><Wrench/><div><h2>Maintenance windows</h2><p>Use maintenance windows to suppress operational noise during planned work.</p></div></div>{items.length?items.map(x=><div className="maintRow" key={x.id}><b>{x.server}</b><span>{new Date(x.start).toLocaleString()} → {new Date(x.end).toLocaleString()}</span><small>{x.reason}</small></div>):<Empty title="No maintenance windows" text="Create a window through the API when planned work is scheduled."/>}</section>}
function SettingsPage(){return <section className="settingsGrid"><Card title="Platform configuration" subtitle="Environment-driven configuration"><Setting k="Prometheus" v={API.includes("localhost")?"Local API proxy":"Configured API"}/><Setting k="Refresh interval" v="30 seconds"/><Setting k="Metrics source" v="Prometheus / Node Exporter"/><Setting k="Time-series store" v="Prometheus (not PostgreSQL)"/></Card><Card title="Security posture" subtitle="Recommended production controls"><Setting k="Authentication" v="JWT + role-based access"/><Setting k="Secrets" v="Environment variables"/><Setting k="SSH" v="Allowlisted diagnostics only"/><Setting k="CORS" v="Explicit frontend origin"/></Card></section>}
function Setting({k,v}){return <div className="setting"><span>{k}</span><b>{v}</b></div>}
function Kpi({icon,label,value,tone}){return <div className="kpi"><div className={`kpiIcon ${tone}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{tone==="good"?"Healthy":tone==="danger"?"Needs attention":"Live telemetry"}</small></div></div>}
function Card({title,subtitle,children}){return <div className="card"><div className="cardHeader"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div></div>{children}</div>}
function AlertRow({alert}){return <div className="alertRow"><div className={`alertIcon ${alert.labels?.severity}`}><AlertTriangle size={16}/></div><div><b>{alert.labels?.alertname}</b><p>{alert.annotations?.description}</p></div><time>{alert.labels?.instance}</time></div>}
function Status({status}){return <span className={`status ${status==="UP"?"up":"down"}`}><i/>{status}</span>}
function Meter({value=0}){const n=Math.round(value||0);return <div className="meterCell"><div className="meter"><i style={{width:`${Math.min(n,100)}%`}}/></div><b>{n}%</b></div>}
function Health({value=0}){return <div className="health"><CircleGauge size={15}/><b>{Math.round(value)}%</b></div>}
function Empty({title,text}){return <div className="empty"><ShieldAlert size={22}/><b>{title}</b><p>{text}</p></div>}
function formatBps(v=0){if(v>1e9)return `${(v/1e9).toFixed(1)} Gbps`;if(v>1e6)return `${(v/1e6).toFixed(0)} Mbps`;if(v>1e3)return `${(v/1e3).toFixed(0)} Kbps`;return `${Math.round(v)} bps`}
function formatUptime(sec=0){if(!sec)return "N/A";const d=Math.floor(sec/86400);const h=Math.floor((sec%86400)/3600);return `${d}d ${h}h`}
createRoot(document.getElementById("root")).render(<App/>);
